echo "We are trying this practical from linux EC2"
echo "We are from batch-24 and learning git/gihub"
echo "Happy weekend"
echo "we are testing-git in lecture 59"
echo "wer are doing mofify"
echo "we are adding new line" 
echo "we are add 3 line"
echo "todya is saturday"
echo "we are adding this line when we are learning branch"
echo "ading new line
"
